Repository labcif/GBoard4A, pull requests merged in 2021-05, with the labels that each got.

#9 autopsy: add support for trainingcache2 in the data source module
  gboard_autopsy.py
  source/gboardforensics/models/trainingcache.d
Labels: feature

#19 Fix string literal to be static immutable
  source/gboardforensics/gatherers/trainingcache.d
Labels: trivial

#26 models: import asdf instead of implicit dependency
  source/gboardforensics/models/trainingcache.d
Labels: trivial

#25 serialization: empty lists are reported as `null` instead of `[]`
  source/gboardforensics/models/clipboard.d
  source/gboardforensics/models/dictionary.d
  source/gboardforensics/models/trainingcache.d
  source/gboardforensics/utils/serialization.d
Labels: bug, trivial
